---
title: "aim2"
author: "Hannah Olson-Williams, Amy Cochran"
format: 
  docx:
    message: false
    warning: false
    echo: false
editor: visual
bibliography: references.bib
---

```{r set up }
library(tidyverse)
library(ggplot2)
library(table1)
load("data_processed/migterm_imp.Rdata")
```

## Abstract

Although the relationship between place and health is well studied and measured, typical place-based measures of health are static, representing a single point in time without accounting for movement or mobility. Among the well-established understanding that place influences health is the understanding that place differentially impacts some groups of people more than others. What remains unknown is to what extent population migration explains place-based health and health disparities. Thus, there is a critical need to measure the degree to which county-level patterns in health factors and outcomes can be attributed to county-level patterns in mobility. Without such knowledge, we are unable to fully capture the complexities of county-level health, limiting our ability to inform local policy making.

This paper aims to provide understanding of the mechanisms by which mobility may be related to place-based health disparities so that local decision-makers may account for patterns in mobility when creating policy towards improved health for all people in all places. In this paper, we quantify and devise techniques for quantifying the relationship between county-level mobility and county-level health. Understanding rural-urban mobility patterns is a necessary first step towards understanding place-based health disparities.

## Introduction 

We are still discovering how changes in our geographical location relate to our health. Geographical changes can happen *to* a person, by either staying in a geographical location that changes around them or moving to a new location. They can also happen *by* a person: when individuals move, not only do they experience a change in location, but they take their sociodemographic identities, income, health, employment, and education with them. As a result, the place they are leaving and the place they are arriving changes, if only slightly. In aggregate, composition changes at a geographic location could potentially change the health of the population as a whole. In this paper, we explore methods for accounting for composition changes due to migration when measuring average health outcomes across U.S. counties.

Measuring health outcomes has been important for guiding effective policy-making. The idea is to identify potential factors that may influence health so that policy-makers can design precise, well-founded strategies. In this regard, it is important for policy-makers to separate changes in average health outcomes that stem from the built environment as opposed to the composition of the population itself. If the built environment is the cause, enhancing access to parks, medical facilities, and public transport might be a solution. If, however, composition changes are the cause, policy-makers may want to learn about their the new residents. This insight will allow for a more tailored approach to meet their specific needs, such as providing affordable housing for low-income families. County-level data and analyses have been valuable tools in gaining this insight, serving to inform local policies on how to raise the average health of a county or reduce disparities within a county <!--# cite -->. This approach has proven especially valuable in the face of challenges like the COVID pandemic, where local entities like health departments, school boards, and faith-based organizations played a pivotal role in responding to public health needs based on county data.

Traditional approaches to county-level analyses of health involve autoregressive models that account for variation across space and time. The application of autoregressive models at the county level has seen various implementations, such as a county's relative position and historical mortality rates for forecasting future mortality rates [@yang2011], or estimating mortality rates that adjusts for county-level information on income and employment, population density and rurality, and race/ethnicity [@anappli]. Similarly, during the early stages of the COVID-19 pandemic, a spatial autoregressive model was utilized to assess the relationships between county-level COVID-19 mortality rates and county-level sociodemographic characteristics [@fielding-miller2020]. This modeling approach has also been applied to age-group and country-level data to explain cohort effects within countries[@li2021], and more recently, to enhance the estimation of country-level life expectancy, particularly for younger demographics, with improved efficiency and accuracy [@shi2021].

These modeling approaches, however, overlook the aspect of migration.  An important consideration is how much of the variation in a county’s average health outcomes could be attributed to the movement of individuals between regions. As a first hypothesis, we might anticipate that a person moving from a region with better (worse) average health outcomes to one with worse (better) average outcomes would increase (decrease) the average health outcomes of their destination, however slightly. If this is true, then models that ignore this source of variation may incorrectly attribute a change in average health outcomes to other factors, such as the built environment.  

A major drawback with this first hypothesis is that it assumes that when a person moves from one place to another, their health status is representative of the average health status of the place they are coming from. In other words, movers are neither more nor less likely to be healthier than the general population of their original location, making their health outcomes comparable to the average health outcomes of that area. Previous research suggests this assumption is not accurate, indicating that the health of migrants often differs from the average health of their origin in addition to the average health of their destination.

To start, migration can have a direct impact on the health of the individual moving. For example, relocation from rural areas to urban areas has been associated with increased risk of cardiovascular disease in some populations [@miranda2011]. Similarly, relocation to high-income countries has been associated with adverse cardiovascular health effects [@agyemang2019]. Several studies have found that rates of cardiovascular disease are higher among migrants than among their peers who did not migrate[@agyemang2022]. For instance, a study of people who migrated to the US from Japan found that Japanese migrants to California had age-adjusted prevalence rates of cardiovascular disease that were more than twice as high as their peers who migrated to Hawaii or did not migrate at all [@marmot1975]. This suggests that the average health of migratory populations becomes more similar to the average health of their destination than that of their origin, possibly because migrants take on the diets, habits, and other health factors of the place to which they relocate.

Another explanation is that people who move are systematically different than people who stay. That is, migration is not random, but selective. According to Lee’s theory [@lee1966], migration is influenced by “push” factors that compel people to leave their origins, due to hardships like job losses, climate events, or war, and by “pull” factors that attract people to new destinations, often favoring those with high income or education. Consequently, migration typically involves either the most advantaged or the least advantaged individuals. This logic might extend to the health of migrants: only the most and least healthy individuals migrate. For example, when the barriers between origin and destination are particularly high, migrants are often healthier on average than the people living in their destination, because unhealthy people are less likely to move when the barriers are high [@halliday2008]. In the aforementioned study of migrants from Japan, for instance, it is possible that people who migrated to California were “pushed” to California while people who migrated from Japan to Hawaii were “pulled” to Hawaii.  

Because migration is selective, a second hypothesis might be that certain factors about a county help explain the relationship between average health of a county and the average health of the counties from which people are moving.  For example, migrants who move from more resource depleted regions to less resource depleted regions often have better health on average than the population in their destination while migrants who move from less depleted regions to more depleted regions have worse health on average than the population in their destination [@norman2005]. One specific factor of interest is urbanicity, because, for one reason, urban and rural regions differ in their average health. For instance, higher rates of high quality of life in Finland were found in rural areas but not after controlling for perceived loneliness[@weckroth2022], and people in urban areas have higher prevalence of both depression and anxiety despite a lower prevalence of other risk factors [@zijlema2015]. For another reason, urban and rural regions differ in ways that relate back to the health of their population, such as access to green space[@tsai2018]; concentration of populations marginalized from resources, crowded living conditions, and air pollution[@ha2017]; access to social organizations[@yang2019], and educational and financial opportunities[@ha2019]. Therefore, if the second hypothesis is true, then we may want to let county factors, like urbanicity, modify how compositional changes due to migration relate to average county health in our modeling. 

Still, even if we accounted for county factors, there may still be *unobserved* factors at play. For example, some people may choose to live in urban places and others in rural environments. These choices could be influenced by the past and present sociocultural context of each community which affects who feels welcomed into which communities. Factors such as personality and familial ties play large roles in both health and choice of living location [@chan1977]. Thus, we arrive at a third hypothesis, in which unobserved factors help explain the relationship average health of a county and the health of the counties from which people are moving. If true, then we may want to investigate the potential for unobserved factors to modify how compositional changes due to migration are incorporated into the model. 

In this paper, we propose novel extensions of traditional spatiotemporal models to account for compositional changes due to migration. Our broad strategy is to use migration flows in and out of counties to adjust the autoregressive term in the model in a principled way. By way of this strategy, we are able to first, formalize and, then, test three hypotheses:

1.  County-to-county migration flows improve the explainability of autoregressive models of county-level health outcomes.

2.  The role that county-to-county migration flows plays in county-level health outcomes differs significantly between rural and urban counties.

3.  Taking into account unmeasured factors in county-to-county migration flows improves our ability to explain county-level health outcomes as well as the differential role that migration plays in urban versus rural counties.

We note these hypotheses mirror the three broad hypotheses introduced earlier. Using publicly accessible mortality data from CDC WONDER [@cdcwond]and county-to-county migration flow data from the IRS [@soitax], we investigate these hypotheses, focusing specifically on county-level premature age-adjusted mortality and on using Bayesian information criteria (BIC) as a measure of model fit. Through this investigation, we seek to demonstrate our strategy for incorporating migration into spatiotemporal models of average health. Additionally, we seek to determine what our modeling strategies reveal about the relationship between county-to-county migration and county-level premature age-adjusted mortality, especially as it relates to urbanicity and the possible influence of unmeasured factors. 

## Methods 

#### Data and Variables 

All of the data used in these analyses is publicly accessible. We use county-level estimates of premature age-adjusted mortality available through the CDC WONDER Underlying Cause of Death 1999-2020 database[@underlyi] joined with IRS county-to-county migration flow data[@soitax].

[The outcome of interest is county-level age-adjusted rates of premature mortality]{.underline} We refer the age-adjusted premature mortality rate for each destination county $i$ at year $t$ as $y_{it}$. Premature mortality is defined as any death occurring before age 75. Age-adjusted rates of premature mortality are commonly used as a gold standard when comparing various dimensions of health across counties since death has a clear and common definition [@self-rat1997; @jylhä2009; @olson-williams2023], and since premature age-adjusted mortality has important policy and health equity implications and can be used to assess which individuals or groups are likely to live longest and which individuals or groups may be most in need of additional care. For our analyses, we excluded years after and including 2020 because the onset of the pandemic is unrelated to other factors included in our model. Additionally, to match migration data, we excluded years prior to 2011. Therefore, we include premature age-adjusted mortality rates for 8 years total (2011 through 2019) for each destination county $i$.

A necessary baseline explanatory factor is [lagged premature age-adjusted mortality]{.underline}, which we refer to as $y_{i,t-1}$. This is our autoregressive term. In order to predict future age-adjusted rates of premature mortality, we use the age-adjusted premature mortality rate of the prior year $(t-1)$ for each destination county $i$.

[An explanatory factor of interest is urbanicity.]{.underline} To assess urbanicity, we assign each county an urbanicity category based on the 2013 National Center for Health Statistics (NCHS) Urban–Rural Classification Scheme for Counties [@rothwell]. To maximize the number of counties per category and improve precision, we chose to use only two urbanization categorizations: urban and rural, where urban includes large central metro, medium metro, and small metro counties, and rural includes micropolitan and noncore counties. We assessed `r length(unique(migterm_imp$destid[migterm_imp$rural == 1]))` unique rural counties and `r length(unique(migterm_imp$destid[migterm_imp$rural == 0]))` unique urban counties.

[The primary explanatory factor of interest is a weighted-average *migration term*]{.underline} which we refer to as $mig_{it}$. We calculate $mig_{it}$ for each destination county $i$ during each year $t$ using the following equation: The migration term $mig_{it}$ accounts for the premature age-adjusted mortality rates of individuals who have moved to a county of interest during a given period. This term is essentially a weighted average of the mortality rates of all of the origin counties $j$ for a given destination county $i$. We calculate the following for each change in year $t$ and for each destination county $i$:

$$  mig_{it} = \frac{ \sum_{j\ne i} out_{jit} y_{j,t-1} + y_{i,t-1} (pop_{i, t-1} - \sum_{j\ne i} out_{ijt})}{ \sum_{j\ne i} out_{jit} + (pop_{i,t-1} - \sum_{j\ne i} out_{ijt})} $$

where $y_{i,t-1}$ is the lagged premature age-adjusted mortality rate of destination county $i$ as defined above and $pop_{i, t-1}$ is the population under age 75 of an unique destination county $i$ at initial year $t-1$. Both $y_{i,t-1}$ and $pop_{i,t-1}$ come from the CDC WONDER Underlying Cause of Death database. The $out_{ijt}$ term represents the number of migrants from a unique origin county $j$ who migrated to a destination county $i$ between year $t-1$ and year $t$. The values of $out_{ijt}$ come from IRS migration flow data from 2011 through 2019. We exclude years prior to 2011 because in 2011 the IRS changed their methods to produce migration estimates based on a full year of income tax filings rather than a partial year. Prior to 2011, migration estimates represented between 95 and 98 percent of total annual income tax filings and excluded income taxes filed after September of each calendar year [@pierce2015]; estimates after 2011 include all annual income tax filings collected for each year. Therefore, we have chosen only to include data after the 2011 change in IRS methodology. We have chosen to use IRS rather than ACS estimates of migration because ACS does not publish single year estimates of migration (only five year estimates), we want to emphasize the temporal aspects of migration, necessitating the use of IRS single year estimates. <!--# something here about the percent of americans who file taxes each year -->

<!--# perhaps smig should go here -->

Since we are particularly interested in spatial trends in premature mortality and migration, we exclude counties from Hawaii and Alaska and include only contiguous counties. Additionally, to avoid systematically excluding counties with small population size and to ensure that we have balanced panel data, we used the mice R package[@mice] to impute lagged premature age-adjusted mortality rates $y_{i,t-1}$ for counties with missing values. There are a total of `r length(unique(migterm_imp$destid))` US counties included in our analyses.

<!--# The map below shows the most recent year of premature age-adjusted mortality rates for the counties included in our analyses. This map also highlights the spatial distribution of county-level premature age-adjusted mortality rates across the United States where Southwestern counties tend to have higher rates of premature mortality than counties in the Midwest and Northeast. -->

## Model fitting 

Using the data and variables outlined above, we first established a baseline autoregressive spatial error model of county-level premature age-adjusted mortality $y_{it}$. The baseline model is as follows:

$$  y_{it} = \beta_0 + \beta_{1t} + \beta_{2}y_{t-1,i} + \mu_{i} + \epsilon_{it}    $$

where $\beta_{1t}$ is a coefficient for the affect of each year $t$ on county-level premature age-adjusted mortality $y_{it}$, $\beta_2$ is a coefficient for the effect of lagged premature age-adjusted mortality on predicted premature mortality, $\mu_i$ is a random intercept for each destination county $i$, and $\epsilon_{it}$ represents an error term accounting for spatial dependencies. We define the equation for spatial dependency as follows:

$$ \epsilon_{it} = \lambda W \epsilon_{it} + u_{it}   $$

Thus, the magnitude of spatial dependency results from the product of $\lambda$, the spatial autoregressive scalar, which is close to 0 when there is no spatial interdependence and increases as spatial interdependence grows, and $W$, a spatial weights matrix with row-standardized weights. We created $W$ using the `spdep` R package [@spdep] with the "queen" criterion which considers counties that share any point as neighbors. Finally, $u_{it}$ represents the spatially independent random error term for each county $i$ at year $t$.<!--# need more context here -->

We created this baseline model and all subsequent models using the `splm` and `splines` R packages [@splines; @splm-2]. To establish a model with the most explanatory power, we began by iteratively adding splines with two to five degrees of freedom for the lagged age-adjusted county-level premature mortality rates $y_{i,t-1}$ to capture potential nonlinear trends over time. We compared models using the Bayesian Information Criterion (BIC), which is commonly used to identify models with the greatest explanatory power[@kuha2004].

Next, we added the migration term $mig_{it}$ to this baseline model. We again attempted to capture nonlinear trends over time by iteratively adding splines with two to five degrees of freedom for the lagged age-adjusted county-level premature mortality rates $y_{i,t-1}$ and the migration term $mig_{it}$. <!--# We observed that keeping the degrees of freedom equal for the splines of both $y_{it}$ and $mig_{it}$ resulted in lower BIC scores, indicating better model fit, so we tested models where the degrees of freedom for $mig_{it}$ and $y_{it}$ were equal.  does this go in results instead?--> The addition of this weighted average migration term to our model allows us to implicitly account for between-county selection for migration. However, $mig_{it}$ does not account for within-county selection of migrants. In other words, our best guess for the mortality rate of migrants is exactly the mortality rate of their original county; meanwhile, some counties are more likely to be destinations for migration than others.

To determine whether the role that county-to-county migration flows play in county-level health outcomes differs significantly between rural and urban counties (Hypothesis 2), we added a factor term for urbanicity including interaction terms between urbanicity and $y_{i,t-1}$ and urbanicity and $mig_{i,t}$. We again compared these models using BIC while iteratively adding splines with two to five degrees of freedom for migration and lagged premature mortality.

Finally, to determine whether taking into account unmeasured factors in county-to-county migration flows improves our ability to explain county-level health outcomes (Hypothesis 3), we added parameters $k_{ij}$ and $l_i$ to the premature mortality rate of each origin $j$ and each destination $i$ within our equation for the migration term. We call this new simulated migration term $smig_{it}$. The equation for $smig_{it}$ is shown below:

$$  smig_{it}(k_{ij}, l_i) = \frac{ \sum_{j\ne i} out_{jit} ( y_{j,t-1} + k_{ij}) + (y_{i,t-1} + l_i) (pop_{i, t-1} - \sum_{j\ne i} out_{ijt})}{ \sum_{j\ne i} out_{jit} + (pop_{i,t-1} - \sum_{j\ne i} out_{ijt})} $$

We use $smig_{it}$ to simulate within-county selection for migration: when the parameter $k_{ij}$ is subtracted (ie decreased mortality rate), we simulate migration by individuals who are healthier than the average of their origin $j$. When the parameter $k_{ij}$ is added (ie increased mortality rate), we simulate migration by individuals who are unhealthier than the average of their origin $j$. Likewise, when the parameter $l_i$ is subtracted (ie decreased mortality rate), we simulate migration by individuals who are healthier than the average of their destination $i$. When the parameter $l_i$ is added (i.e., increased mortality rate), we simulate migration by individuals who are unhealthier than the average of their origin $i$. We specify that $k_{ij}$ depends on both origin $j$ and destination $i$ since health related selection for migration is connected to both the origins and the destinations of counties; meanwhile $l_i$ is dependent only upon the health of destination $i$.

Since we are most interested in how the values of $k_{ij}$ and $l_i$ are related to each other, we chose to simplify $smig_{it}$ such that $l_i$ is held constant and only $k_{ij}$ fluctuates. Therefore, we assign the parameter $d_{ij}$ to be the difference between $k_{ij}$ and $l_i$, thus creating a new equation for $k_{ij}$ in terms of $l_i$ and $d_{ij}$ such that $k_{ij} = l_i+ d_{ij}$. The value of $d_{i,j}$ can be thought of as a modeling term to explain health-related selection bias. <!--# amy's phrasing: "refer to the dij as a modeling term that models health related selection bias" -->Then our equation for $smig_{it}(k_{ij})$ becomes:

$$  smig_{it}(l_i+d_{ij}, l_i) = \frac{ \sum_{j\ne i} out_{jit} ( y_{j,t-1} + l_i + d_{ij}) + (y_{i,t-1} +l_i)( pop_{i, t-1} - \sum_{j\ne i} out_{ijt})}{ \sum_{j\ne i} out_{jit} + (pop_{i,t-1} - \sum_{j\ne i} out_{ijt})} $$

which can be simplified into the following:

$$  smig_{it}(d_{ij}) = \frac{ \sum_{j\ne i} out_{jit} ( y_{j,t-1} + d_{ij}) + y_{i,t-1} (pop_{i, t-1} - \sum_{j\ne i} out_{ijt})}{ \sum_{j\ne i} out_{jit} + (pop_{i,t-1} - \sum_{j\ne i} out_{ijt})} +l_i$$

Therefore, using the equation above, we simulate health-related selection occurring as a result of the differences in health between the origin and the destination counties. When $d_{ij}$ is positive, we estimate that the origin is less healthy than the destination. When $d_{ij}$ is negative, we estimate that the origin is healthier than the destination.

To determine which values of $d_{ij}$ best explain trends in county-level premature mortality rates, we replace $mig_{it}$ with $smig_{it}(d_{ij})$ in the model with the most explanatory power as determined in our previous model selection steps.
